
package com.persen.beijing.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "BssImprestChargeServicePortType", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface BssImprestChargeServicePortType {


    /**
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @param in6
     * @param in7
     * @return returns java.lang.String
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
    @RequestWrapper(localName = "bssCharge", targetNamespace = "http://webservice.service.business.sncp.woniu.com", className = "com.persen.beijing.webservice.BssCharge")
    @ResponseWrapper(localName = "bssChargeResponse", targetNamespace = "http://webservice.service.business.sncp.woniu.com", className = "com.persen.beijing.webservice.BssChargeResponse")
    public String bssCharge(
            @WebParam(name = "in0", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in0,
            @WebParam(name = "in1", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in1,
            @WebParam(name = "in2", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in2,
            @WebParam(name = "in3", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in3,
            @WebParam(name = "in4", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in4,
            @WebParam(name = "in5", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in5,
            @WebParam(name = "in6", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in6,
            @WebParam(name = "in7", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in7)
            throws ServiceException_Exception
    ;

    /**
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @param in6
     * @param in7
     * @param in8
     * @return returns java.lang.String
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
    @RequestWrapper(localName = "bssChargeByDealflag", targetNamespace = "http://webservice.service.business.sncp.woniu.com", className = "com.persen.beijing.webservice.BssChargeByDealflag")
    @ResponseWrapper(localName = "bssChargeByDealflagResponse", targetNamespace = "http://webservice.service.business.sncp.woniu.com", className = "com.persen.beijing.webservice.BssChargeByDealflagResponse")
    public String bssChargeByDealflag(
            @WebParam(name = "in0", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in0,
            @WebParam(name = "in1", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in1,
            @WebParam(name = "in2", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in2,
            @WebParam(name = "in3", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in3,
            @WebParam(name = "in4", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in4,
            @WebParam(name = "in5", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in5,
            @WebParam(name = "in6", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in6,
            @WebParam(name = "in7", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in7,
            @WebParam(name = "in8", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in8)
            throws ServiceException_Exception
    ;

    /**
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @param in6
     * @param in7
     * @return returns java.lang.String
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
    @RequestWrapper(localName = "bssImprest", targetNamespace = "http://webservice.service.business.sncp.woniu.com", className = "com.persen.beijing.webservice.BssImprest")
    @ResponseWrapper(localName = "bssImprestResponse", targetNamespace = "http://webservice.service.business.sncp.woniu.com", className = "com.persen.beijing.webservice.BssImprestResponse")
    public String bssImprest(
            @WebParam(name = "in0", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in0,
            @WebParam(name = "in1", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in1,
            @WebParam(name = "in2", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in2,
            @WebParam(name = "in3", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in3,
            @WebParam(name = "in4", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in4,
            @WebParam(name = "in5", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in5,
            @WebParam(name = "in6", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in6,
            @WebParam(name = "in7", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in7)
            throws ServiceException_Exception
    ;

    /**
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @param in6
     * @param in7
     * @param in8
     * @return returns java.lang.String
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
    @RequestWrapper(localName = "bssCoreCharge", targetNamespace = "http://webservice.service.business.sncp.woniu.com", className = "com.persen.beijing.webservice.BssCoreCharge")
    @ResponseWrapper(localName = "bssCoreChargeResponse", targetNamespace = "http://webservice.service.business.sncp.woniu.com", className = "com.persen.beijing.webservice.BssCoreChargeResponse")
    public String bssCoreCharge(
            @WebParam(name = "in0", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in0,
            @WebParam(name = "in1", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in1,
            @WebParam(name = "in2", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in2,
            @WebParam(name = "in3", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in3,
            @WebParam(name = "in4", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in4,
            @WebParam(name = "in5", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in5,
            @WebParam(name = "in6", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in6,
            @WebParam(name = "in7", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in7,
            @WebParam(name = "in8", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in8)
            throws ServiceException_Exception
    ;

    /**
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in9
     * @param in5
     * @param in6
     * @param in7
     * @param in8
     * @return returns java.lang.String
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
    @RequestWrapper(localName = "bssCoreChargeByDealflag", targetNamespace = "http://webservice.service.business.sncp.woniu.com", className = "com.persen.beijing.webservice.BssCoreChargeByDealflag")
    @ResponseWrapper(localName = "bssCoreChargeByDealflagResponse", targetNamespace = "http://webservice.service.business.sncp.woniu.com", className = "com.persen.beijing.webservice.BssCoreChargeByDealflagResponse")
    public String bssCoreChargeByDealflag(
            @WebParam(name = "in0", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in0,
            @WebParam(name = "in1", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in1,
            @WebParam(name = "in2", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in2,
            @WebParam(name = "in3", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in3,
            @WebParam(name = "in4", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in4,
            @WebParam(name = "in5", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in5,
            @WebParam(name = "in6", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in6,
            @WebParam(name = "in7", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in7,
            @WebParam(name = "in8", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in8,
            @WebParam(name = "in9", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in9)
            throws ServiceException_Exception
    ;

    /**
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @param in6
     * @return returns java.lang.String
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
    @RequestWrapper(localName = "bssChangePasswd", targetNamespace = "http://webservice.service.business.sncp.woniu.com", className = "com.persen.beijing.webservice.BssChangePasswd")
    @ResponseWrapper(localName = "bssChangePasswdResponse", targetNamespace = "http://webservice.service.business.sncp.woniu.com", className = "com.persen.beijing.webservice.BssChangePasswdResponse")
    public String bssChangePasswd(
            @WebParam(name = "in0", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in0,
            @WebParam(name = "in1", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in1,
            @WebParam(name = "in2", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in2,
            @WebParam(name = "in3", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in3,
            @WebParam(name = "in4", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in4,
            @WebParam(name = "in5", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in5,
            @WebParam(name = "in6", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in6)
            throws ServiceException_Exception
    ;

    /**
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @return returns java.lang.String
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
    @RequestWrapper(localName = "tutuAccountQuery", targetNamespace = "http://webservice.service.business.sncp.woniu.com", className = "com.persen.beijing.webservice.TutuAccountQuery")
    @ResponseWrapper(localName = "tutuAccountQueryResponse", targetNamespace = "http://webservice.service.business.sncp.woniu.com", className = "com.persen.beijing.webservice.TutuAccountQueryResponse")
    public String tutuAccountQuery(
            @WebParam(name = "in0", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in0,
            @WebParam(name = "in1", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in1,
            @WebParam(name = "in2", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in2,
            @WebParam(name = "in3", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in3,
            @WebParam(name = "in4", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in4,
            @WebParam(name = "in5", targetNamespace = "http://webservice.service.business.sncp.woniu.com")
                    String in5)
            throws ServiceException_Exception
    ;

}
