
package com.persen.beijing.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "Hello", targetNamespace = "http://webservice.beijing.persen.com/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface Hello {


    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://webservice.beijing.persen.com/", className = "com.persen.beijing.webservice.Hello_Type")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://webservice.beijing.persen.com/", className = "com.persen.beijing.webservice.HelloResponse")
    @Action(input = "http://webservice.beijing.persen.com/Hello/helloRequest", output = "http://webservice.beijing.persen.com/Hello/helloResponse")
    public String hello(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello1", targetNamespace = "http://webservice.beijing.persen.com/", className = "com.persen.beijing.webservice.Hello1")
    @ResponseWrapper(localName = "hello1Response", targetNamespace = "http://webservice.beijing.persen.com/", className = "com.persen.beijing.webservice.Hello1Response")
    @Action(input = "http://webservice.beijing.persen.com/Hello/hello1Request", output = "http://webservice.beijing.persen.com/Hello/hello1Response")
    public String hello1(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
